export { default as CreateLaboratoryModal } from './CreateLaboratoryModal';
export { default as EditLaboratoryModal } from './EditLaboratoryModal';
export { default as CreateDepartmentModal } from './CreateDepartmentModal';
export { default as EditDepartmentModal } from './EditDepartmentModal';
export { default as SaveCalculationModal } from './SaveCalculationModal';
export { default as SaveSampleCalculationModal } from './SaveSampleCalculationModal';
export { default as CreateResearchMethodModal } from './CreateResearchMethodModal';
export { CreateSampleModal } from './CreateSampleModal';
export { EditSampleModal } from './EditSampleModal';
export { default as CreateBranchModal } from './CreateBranchModal';
export { default as EditBranchModal } from './EditBranchModal';
export { default as DeleteBranchModal } from './DeleteBranchModal';
export { default as CreateSamplingLocationModal } from './CreateSamplingLocationModal';
export { default as EditSamplingLocationModal } from './EditSamplingLocationModal';
export { default as DeleteSamplingLocationModal } from './DeleteSamplingLocationModal';
