"""Константы отчётов ИЛНиНМ."""

SAMPLING_LOCATION_CDGGKN_1 = "Цех по ДГГКН №1"
SAMPLING_LOCATION_CDGGKN_2 = "Цех по ДГГКН №2"
SAMPLING_LOCATIONS_CDGGKN = (SAMPLING_LOCATION_CDGGKN_1, SAMPLING_LOCATION_CDGGKN_2)

SAMPLING_LOCATION_DISPLAY_CDGGKN_1 = "ЦДГГКН №1"
SAMPLING_LOCATION_DISPLAY_CDGGKN_2 = "ЦДГГКН №2"
DISPLAY_NAMES_CDGGKN = {
    SAMPLING_LOCATION_CDGGKN_1: SAMPLING_LOCATION_DISPLAY_CDGGKN_1,
    SAMPLING_LOCATION_CDGGKN_2: SAMPLING_LOCATION_DISPLAY_CDGGKN_2,
}

DISPLAY_TO_DB_NAME_CDGGKN = {
    SAMPLING_LOCATION_DISPLAY_CDGGKN_1: SAMPLING_LOCATION_CDGGKN_1,
    SAMPLING_LOCATION_DISPLAY_CDGGKN_2: SAMPLING_LOCATION_CDGGKN_2,
    SAMPLING_LOCATION_CDGGKN_1: SAMPLING_LOCATION_CDGGKN_1,
    SAMPLING_LOCATION_CDGGKN_2: SAMPLING_LOCATION_CDGGKN_2,
}

DB_NAME_TO_DISPLAY_CDGGKN = DISPLAY_NAMES_CDGGKN

PHYSICOCHEMICAL_SAMPLING_LOCATION_OPTIONS = (
    SAMPLING_LOCATION_DISPLAY_CDGGKN_1,
    SAMPLING_LOCATION_DISPLAY_CDGGKN_2,
)
