"""migration3

Revision ID: 2a2272d64c04
Revises: 781a3fa4e10d
Create Date: 2026-01-13 10:26:26.650270

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a2272d64c04"
down_revision = "781a3fa4e10d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "equipments",
        sa.Column(
            "method_data_default",
            sa.JSON(),
            nullable=True,
            comment="Методы по умолчанию",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("equipments", "method_data_default")
    # ### end Alembic commands ###
