"""migration1

Revision ID: 53a882c8c9b4
Revises: 60b7ecdf3725
Create Date: 2025-12-31 22:56:04.847564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a882c8c9b4'
down_revision = '60b7ecdf3725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('added_by', sa.String(length=150), nullable=True, comment='hsnils лица, добавившего пробу'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'added_by')
    # ### end Alembic commands ###
