"""migration

Revision ID: 60b7ecdf3725
Revises: 14ca60070096
Create Date: 2025-12-23 11:36:22.508657

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "60b7ecdf3725"
down_revision = "14ca60070096"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "well_modes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Название режима скважины",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_by_hash", sa.String(length=32), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by_hash", sa.String(length=32), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column("deleted_by_hash", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["laborant.branches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="laborant",
    )
    op.create_index(
        "idx_well_mode_branch_name",
        "well_modes",
        ["branch_id", "name"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        "idx_well_mode_created_at",
        "well_modes",
        ["created_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        "idx_well_mode_updated_at",
        "well_modes",
        ["updated_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_branch_id"),
        "well_modes",
        ["branch_id"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_created_at"),
        "well_modes",
        ["created_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_created_by"),
        "well_modes",
        ["created_by"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_created_by_hash"),
        "well_modes",
        ["created_by_hash"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_deleted_at"),
        "well_modes",
        ["deleted_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_deleted_by"),
        "well_modes",
        ["deleted_by"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_deleted_by_hash"),
        "well_modes",
        ["deleted_by_hash"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_name"),
        "well_modes",
        ["name"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_updated_at"),
        "well_modes",
        ["updated_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_updated_by"),
        "well_modes",
        ["updated_by"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_well_modes_updated_by_hash"),
        "well_modes",
        ["updated_by_hash"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        "unique_well_mode_per_branch",
        "well_modes",
        ["branch_id", "name"],
        unique=True,
        schema="laborant",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_well_mode_per_branch",
        table_name="well_modes",
        schema="laborant",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_updated_by_hash"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_updated_by"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_updated_at"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_name"), table_name="well_modes", schema="laborant"
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_deleted_by_hash"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_deleted_by"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_deleted_at"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_created_by_hash"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_created_by"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_created_at"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_well_modes_branch_id"),
        table_name="well_modes",
        schema="laborant",
    )
    op.drop_index(
        "idx_well_mode_updated_at", table_name="well_modes", schema="laborant"
    )
    op.drop_index(
        "idx_well_mode_created_at", table_name="well_modes", schema="laborant"
    )
    op.drop_index(
        "idx_well_mode_branch_name", table_name="well_modes", schema="laborant"
    )
    op.drop_table("well_modes", schema="laborant")
    # ### end Alembic commands ###
