"""migration

Revision ID: 781a3fa4e10d
Revises: 53a882c8c9b4
Create Date: 2026-01-12 11:34:25.983623

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "781a3fa4e10d"
down_revision = "53a882c8c9b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "report_type", sa.String(length=255), nullable=False, comment="Тип отчета"
        ),
        sa.Column(
            "version",
            sa.String(length=8),
            nullable=False,
            comment="Версия шаблона (например, v1)",
        ),
        sa.Column("file", sa.String(), nullable=False, comment="Файл (base64)"),
        sa.Column(
            "file_name",
            sa.String(length=255),
            nullable=False,
            comment="Оригинальное имя файла",
        ),
        sa.Column("laboratory_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("created_by_hash", sa.String(length=32), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by_hash", sa.String(length=32), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column("deleted_by_hash", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["laborant.departments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["laboratory_id"], ["laborant.laboratories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="laborant",
    )
    op.create_index(
        "idx_report_template_created_at",
        "report_templates",
        ["created_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        "idx_report_template_department",
        "report_templates",
        ["department_id"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        "idx_report_template_laboratory",
        "report_templates",
        ["laboratory_id"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        "idx_report_template_type",
        "report_templates",
        ["report_type"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        "idx_report_template_updated_at",
        "report_templates",
        ["updated_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_created_at"),
        "report_templates",
        ["created_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_created_by"),
        "report_templates",
        ["created_by"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_created_by_hash"),
        "report_templates",
        ["created_by_hash"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_deleted_at"),
        "report_templates",
        ["deleted_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_deleted_by"),
        "report_templates",
        ["deleted_by"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_deleted_by_hash"),
        "report_templates",
        ["deleted_by_hash"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_report_type"),
        "report_templates",
        ["report_type"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_updated_at"),
        "report_templates",
        ["updated_at"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_updated_by"),
        "report_templates",
        ["updated_by"],
        unique=False,
        schema="laborant",
    )
    op.create_index(
        op.f("ix_laborant_report_templates_updated_by_hash"),
        "report_templates",
        ["updated_by_hash"],
        unique=False,
        schema="laborant",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_laborant_report_templates_updated_by_hash"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_report_templates_updated_by"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_report_templates_updated_at"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_report_templates_report_type"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_report_templates_deleted_by_hash"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_report_templates_deleted_by"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_report_templates_deleted_at"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_report_templates_created_by_hash"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_report_templates_created_by"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        op.f("ix_laborant_report_templates_created_at"),
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        "idx_report_template_updated_at",
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        "idx_report_template_type", table_name="report_templates", schema="laborant"
    )
    op.drop_index(
        "idx_report_template_laboratory",
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        "idx_report_template_department",
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_index(
        "idx_report_template_created_at",
        table_name="report_templates",
        schema="laborant",
    )
    op.drop_table("report_templates", schema="laborant")
    # ### end Alembic commands ###
