"""role type

Revision ID: d4bf3d4b6ae2
Revises: e8ebdbadb7b7
Create Date: 2026-06-25 10:32:46.500887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bf3d4b6ae2'
down_revision = 'e8ebdbadb7b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_type', sa.String(length=20), nullable=False, comment='Тип роли: laborant, engineer'))
    op.create_index(op.f('ix_laborant_roles_created_at'), 'roles', ['created_at'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_roles_created_by'), 'roles', ['created_by'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_roles_created_by_hash'), 'roles', ['created_by_hash'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_roles_deleted_by'), 'roles', ['deleted_by'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_roles_deleted_by_hash'), 'roles', ['deleted_by_hash'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_roles_role_type'), 'roles', ['role_type'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_roles_updated_at'), 'roles', ['updated_at'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_roles_updated_by'), 'roles', ['updated_by'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_roles_updated_by_hash'), 'roles', ['updated_by_hash'], unique=False, schema='laborant')
    op.create_index('unique_role_name_type', 'roles', ['name', 'role_type'], unique=True, schema='laborant', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_laborant_test_objects_created_at'), 'test_objects', ['created_at'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_test_objects_created_by'), 'test_objects', ['created_by'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_test_objects_created_by_hash'), 'test_objects', ['created_by_hash'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_test_objects_deleted_by'), 'test_objects', ['deleted_by'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_test_objects_deleted_by_hash'), 'test_objects', ['deleted_by_hash'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_test_objects_updated_at'), 'test_objects', ['updated_at'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_test_objects_updated_by'), 'test_objects', ['updated_by'], unique=False, schema='laborant')
    op.create_index(op.f('ix_laborant_test_objects_updated_by_hash'), 'test_objects', ['updated_by_hash'], unique=False, schema='laborant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laborant_test_objects_updated_by_hash'), table_name='test_objects', schema='laborant')
    op.drop_index(op.f('ix_laborant_test_objects_updated_by'), table_name='test_objects', schema='laborant')
    op.drop_index(op.f('ix_laborant_test_objects_updated_at'), table_name='test_objects', schema='laborant')
    op.drop_index(op.f('ix_laborant_test_objects_deleted_by_hash'), table_name='test_objects', schema='laborant')
    op.drop_index(op.f('ix_laborant_test_objects_deleted_by'), table_name='test_objects', schema='laborant')
    op.drop_index(op.f('ix_laborant_test_objects_created_by_hash'), table_name='test_objects', schema='laborant')
    op.drop_index(op.f('ix_laborant_test_objects_created_by'), table_name='test_objects', schema='laborant')
    op.drop_index(op.f('ix_laborant_test_objects_created_at'), table_name='test_objects', schema='laborant')
    op.drop_index('unique_role_name_type', table_name='roles', schema='laborant', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_laborant_roles_updated_by_hash'), table_name='roles', schema='laborant')
    op.drop_index(op.f('ix_laborant_roles_updated_by'), table_name='roles', schema='laborant')
    op.drop_index(op.f('ix_laborant_roles_updated_at'), table_name='roles', schema='laborant')
    op.drop_index(op.f('ix_laborant_roles_role_type'), table_name='roles', schema='laborant')
    op.drop_index(op.f('ix_laborant_roles_deleted_by_hash'), table_name='roles', schema='laborant')
    op.drop_index(op.f('ix_laborant_roles_deleted_by'), table_name='roles', schema='laborant')
    op.drop_index(op.f('ix_laborant_roles_created_by_hash'), table_name='roles', schema='laborant')
    op.drop_index(op.f('ix_laborant_roles_created_by'), table_name='roles', schema='laborant')
    op.drop_index(op.f('ix_laborant_roles_created_at'), table_name='roles', schema='laborant')
    op.drop_column('roles', 'role_type')
    # ### end Alembic commands ###
